### ISSUE TITLE
dynamic library be a crash，not working properly

### ISSUE THREAD

**Issue by doudouwa5** [avltree9798/isJailbroken#2]
dynamic library be a crash，not working properly

**Comment by avltree9798** [comment]
Can you please tell me a bit more? The crash log would be very helpful

**Comment by doudouwa5** [comment]
Since I don't have a jailbreak machine, I have to pack it up for testing.
If I open the： BOOL dylibResult = isInjectedWithDynamicLibrary(); 
 it will crash, otherwise it will not.

**Comment by doudouwa5** [comment]
And he can't keep out the sun  Shadow

**Comment by avltree9798** [comment]
> Since I don't have a jailbreak machine, I have to pack it up for testing.
> If I open the： BOOL dylibResult = isInjectedWithDynamicLibrary();
> it will crash, otherwise it will not.

can you provide me the log from lldb / xcode?
