### ISSUE TITLE
Compiler errors due to method name mismatch

### ISSUE THREAD

**Issue by hdsenevi** [avltree9798/isJailbroken#5]
There is an error thrown for `ViewController.isSecurityCheckNotPassed()` when I try to run this project.

![image](https://user-images.githubusercontent.com/886370/92082642-2b30f800-ee08-11ea-821d-13137e9f19d7.png)

Created a PR to fix that here : https://github.com/avltree9798/isJailbroken/pull/4

**Comment by avltree9798** [comment]
Merged! Thanks
