### ISSUE TITLE
Crash when Liberty Lite Block Jailbreak Detection

### ISSUE THREAD

**Issue by zaenalarsy** [avltree9798/isJailbroken#6]
HI @avltree9798 , thank you so much for your awesome work.
I've some issue when i try to target the app to block jailbreak detection with liberty lite then the app will crash, do you have any solution to prevent the crash? and detect that the app is already inject by some tools such as liberty lite instead of crash.

**Comment by avltree9798** [comment]
> HI @avltree9798 , thank you so much for your awesome work.
> I've some issue when i try to target the app to block jailbreak detection with liberty lite then the app will crash, do you have any solution to prevent the crash? and detect that the app is already inject by some tools such as liberty lite instead of crash.

Do you have some-kind of crash log?
